export type AttendanceStatus = 'present' | 'late' | 'absent'

export interface Student {
  id: string
  name: string
  status: AttendanceStatus
  description: string
}

export interface Group {
  id: string
  name: string
  teacher: string
  studentCount: number
  presentCount: number
  lateCount: number
  absentCount: number
  students: Student[]
}

export const mockGroups: Group[] = [
  {
    id: '1',
    name: 'Frontend N23',
    teacher: 'Abdulhakimov Shokh',
    studentCount: 25,
    presentCount: 22,
    lateCount: 2,
    absentCount: 1,
    students: [
      { id: 's1', name: 'Alisher Abdullayev', status: 'present', description: '' },
      { id: 's2', name: 'Botir Akhmedov', status: 'present', description: '' },
      { id: 's3', name: 'Dilshod Karimov', status: 'present', description: '' },
      { id: 's4', name: 'Eko Suryanto', status: 'late', description: 'Kechikti 5 daqiqa' },
      { id: 's5', name: 'Farid Uzbekov', status: 'present', description: '' },
      { id: 's6', name: 'Gafur Hamidov', status: 'present', description: '' },
      { id: 's7', name: 'Husan Mirzoev', status: 'absent', description: 'Bemalol' },
      { id: 's8', name: 'Imomjon Rakhimov', status: 'present', description: '' },
      { id: 's9', name: 'Javohir Tashmatov', status: 'present', description: '' },
      { id: 's10', name: 'Kamol Normurodov', status: 'present', description: '' },
      { id: 's11', name: 'Lola Sayfullaeva', status: 'present', description: '' },
      { id: 's12', name: 'Mirsulton Karimov', status: 'present', description: '' },
      { id: 's13', name: 'Nilufar Bahronova', status: 'present', description: '' },
      { id: 's14', name: 'Oybek Salimov', status: 'present', description: '' },
      { id: 's15', name: 'Parizod Mustafaeva', status: 'present', description: '' },
      { id: 's16', name: 'Qodirjon Hamdamov', status: 'present', description: '' },
      { id: 's17', name: 'Rasul Nasriddinov', status: 'late', description: 'Kechikti 10 daqiqa' },
      { id: 's18', name: 'Saida Abdullayeva', status: 'present', description: '' },
      { id: 's19', name: 'Tohir Ismoilov', status: 'present', description: '' },
      { id: 's20', name: 'Umida Rakhimova', status: 'present', description: '' },
      { id: 's21', name: 'Vasila Sadullayeva', status: 'present', description: '' },
      { id: 's22', name: 'Xurshed Vokhidov', status: 'present', description: '' },
      { id: 's23', name: 'Yusufjon Raxmatov', status: 'present', description: '' },
      { id: 's24', name: 'Zumrad Xamroeva', status: 'present', description: '' },
      { id: 's25', name: 'Zulfiya Nabiyeva', status: 'present', description: '' },
    ],
  },
  {
    id: '2',
    name: 'Backend N23',
    teacher: 'Urinbaev Oleg',
    studentCount: 23,
    presentCount: 21,
    lateCount: 1,
    absentCount: 1,
    students: [
      { id: 's26', name: 'Akram Yuldashev', status: 'present', description: '' },
      { id: 's27', name: 'Behruz Sharifov', status: 'present', description: '' },
      { id: 's28', name: 'Chingiz Hamidov', status: 'present', description: '' },
      { id: 's29', name: 'Dilbar Mustafaeva', status: 'present', description: '' },
      { id: 's30', name: 'Edil Bekmuratov', status: 'present', description: '' },
      { id: 's31', name: 'Farangiz Yousupova', status: 'present', description: '' },
      { id: 's32', name: 'Gulnoza Sharipova', status: 'absent', description: 'Bemalol' },
      { id: 's33', name: 'Hamid Askarov', status: 'present', description: '' },
      { id: 's34', name: 'Ilyos Normurodov', status: 'late', description: 'Kechikti 15 daqiqa' },
      { id: 's35', name: 'Jamilya Tasheva', status: 'present', description: '' },
      { id: 's36', name: 'Kamil Razikov', status: 'present', description: '' },
      { id: 's37', name: 'Lobar Mirzaeva', status: 'present', description: '' },
      { id: 's38', name: 'Mirjalol Mirzoev', status: 'present', description: '' },
      { id: 's39', name: 'Nozim Khakimov', status: 'present', description: '' },
      { id: 's40', name: 'Odinjon Karimov', status: 'present', description: '' },
      { id: 's41', name: 'Parviz Rakhimov', status: 'present', description: '' },
      { id: 's42', name: 'Qayum Suleimanov', status: 'present', description: '' },
      { id: 's43', name: 'Ravshan Nabiyev', status: 'present', description: '' },
      { id: 's44', name: 'Samira Abdullayeva', status: 'present', description: '' },
      { id: 's45', name: 'Toshqori Normatov', status: 'present', description: '' },
      { id: 's46', name: 'Ulugbek Sadullayev', status: 'present', description: '' },
      { id: 's47', name: 'Vildan Ismoilova', status: 'present', description: '' },
      { id: 's48', name: 'Yoldosh Khakimov', status: 'present', description: '' },
    ],
  },
  {
    id: '3',
    name: 'Mobile N23',
    teacher: 'Pulatov Miroj',
    studentCount: 22,
    presentCount: 20,
    lateCount: 2,
    absentCount: 0,
    students: [
      { id: 's49', name: 'Abdulaziz Niyozov', status: 'present', description: '' },
      { id: 's50', name: 'Bahrom Usmanov', status: 'present', description: '' },
      { id: 's51', name: 'Chulpan Khakimova', status: 'present', description: '' },
      { id: 's52', name: 'Dilmurod Yuldashev', status: 'late', description: 'Kechikti 3 daqiqa' },
      { id: 's53', name: 'Eldor Rakhimov', status: 'present', description: '' },
      { id: 's54', name: 'Farida Ismoilova', status: 'present', description: '' },
      { id: 's55', name: 'Gulnar Karimova', status: 'present', description: '' },
      { id: 's56', name: 'Hamida Nazarova', status: 'present', description: '' },
      { id: 's57', name: 'Ilkhom Sharifov', status: 'present', description: '' },
      { id: 's58', name: 'Jasmine Yousupova', status: 'present', description: '' },
      { id: 's59', name: 'Kamron Khalikov', status: 'present', description: '' },
      { id: 's60', name: 'Lorik Mirzoev', status: 'present', description: '' },
      { id: 's61', name: 'Maruf Normurodov', status: 'present', description: '' },
      { id: 's62', name: 'Nazima Tasheva', status: 'present', description: '' },
      { id: 's63', name: 'Olim Khakimov', status: 'present', description: '' },
      { id: 's64', name: 'Parvina Abdullayeva', status: 'present', description: '' },
      { id: 's65', name: 'Quwwat Suleimanov', status: 'late', description: 'Kechikti 7 daqiqa' },
      { id: 's66', name: 'Rashid Nabiyev', status: 'present', description: '' },
      { id: 's67', name: 'Sitora Rakhimova', status: 'present', description: '' },
      { id: 's68', name: 'Timur Ismoilov', status: 'present', description: '' },
      { id: 's69', name: 'Ulanbek Karimov', status: 'present', description: '' },
      { id: 's70', name: 'Vakhida Nazarova', status: 'present', description: '' },
    ],
  },
  {
    id: '4',
    name: 'DevOps N23',
    teacher: 'Rakhmatullin Dmitry',
    studentCount: 20,
    presentCount: 19,
    lateCount: 0,
    absentCount: 1,
    students: [
      { id: 's71', name: 'Adham Yuldashev', status: 'present', description: '' },
      { id: 's72', name: 'Beknur Sharifov', status: 'present', description: '' },
      { id: 's73', name: 'Chingiz Hamidov', status: 'present', description: '' },
      { id: 's74', name: 'Doniyor Karimov', status: 'present', description: '' },
      { id: 's75', name: 'Eldor Normurodov', status: 'absent', description: 'Bemalol' },
      { id: 's76', name: 'Fahim Ismoilnov', status: 'present', description: '' },
      { id: 's77', name: 'Guljon Khakimova', status: 'present', description: '' },
      { id: 's78', name: 'Hamzjon Tashanov', status: 'present', description: '' },
      { id: 's79', name: 'Ilshodjon Yoldashev', status: 'present', description: '' },
      { id: 's80', name: 'Jamoliddin Khalikov', status: 'present', description: '' },
      { id: 's81', name: 'Kamran Rakhimov', status: 'present', description: '' },
      { id: 's82', name: 'Latif Mirzoev', status: 'present', description: '' },
      { id: 's83', name: 'Mansur Sharipov', status: 'present', description: '' },
      { id: 's84', name: 'Nizom Khakimov', status: 'present', description: '' },
      { id: 's85', name: 'Oybek Normurodov', status: 'present', description: '' },
      { id: 's86', name: 'Pako Abdullayev', status: 'present', description: '' },
      { id: 's87', name: 'Qodri Karimov', status: 'present', description: '' },
      { id: 's88', name: 'Rashid Suleimanov', status: 'present', description: '' },
      { id: 's89', name: 'Sukhrob Nasriddinov', status: 'present', description: '' },
      { id: 's90', name: 'Tursunbay Rakhimov', status: 'present', description: '' },
    ],
  },
  {
    id: '5',
    name: 'UI/UX N23',
    teacher: 'Shermatova Elena',
    studentCount: 18,
    presentCount: 17,
    lateCount: 1,
    absentCount: 0,
    students: [
      { id: 's91', name: 'Alfiya Yoldasheva', status: 'present', description: '' },
      { id: 's92', name: 'Basilya Sharipova', status: 'present', description: '' },
      { id: 's93', name: 'Chamila Hamidova', status: 'present', description: '' },
      { id: 's94', name: 'Diana Karimova', status: 'present', description: '' },
      { id: 's95', name: 'Enara Tasheva', status: 'present', description: '' },
      { id: 's96', name: 'Feliya Ismoilova', status: 'late', description: 'Kechikti 12 daqiqa' },
      { id: 's97', name: 'Gulchehra Khakimova', status: 'present', description: '' },
      { id: 's98', name: 'Hadija Rakhimova', status: 'present', description: '' },
      { id: 's99', name: 'Ilvina Nazarova', status: 'present', description: '' },
      { id: 's100', name: 'Jalila Yousupova', status: 'present', description: '' },
      { id: 's101', name: 'Kamilla Normurodova', status: 'present', description: '' },
      { id: 's102', name: 'Lilia Abdullayeva', status: 'present', description: '' },
      { id: 's103', name: 'Marjona Sharifova', status: 'present', description: '' },
      { id: 's104', name: 'Nigina Khalikova', status: 'present', description: '' },
      { id: 's105', name: 'Olmajon Khakimova', status: 'present', description: '' },
      { id: 's106', name: 'Parvina Rakhimova', status: 'present', description: '' },
      { id: 's107', name: 'Quyosh Karimova', status: 'present', description: '' },
      { id: 's108', name: 'Raimona Nasriddinova', status: 'present', description: '' },
    ],
  },
]
